/*
 * To change this license header"), choose License Headers in Project Properties.
 * To change this template file"), choose Tools | Templates
 * and open the template in the editor.
 */
package org.mediaserv.fibre.protocole.domain.acces;

/**
 *
 * @author RREMBLIN
 */
public enum Rejet {
FCLI01("FCLI01"),//CLIENT : CONTACT ERRONE
FCLI02("FCLI02"),//CLIENT : CLIENT INJOIGNABLE IMPOSSIBLE DE PRENDRE RDV
FCLI03("FCLI03"),//CLIENT : CLIENT N HABITE PAS A L ADRESSE INDIQUEE
FCLI04("FCLI04"),//CLIENT : DEMANDE ANNULATION DE LA COMMANDE PAR LE CLIENT FINAL
FCLI05("FCLI05"),//CLIENT : REFUS TRAVAUX CLIENT 
FCLI06("FCLI06"),//CLIENT : REFUS GESTIONNAIRE IMMEUBLE
FCLI07("FCLI07"),//CLIENT : CLIENT ABSENT LORS DE L INTERVENTION
FADR01("FADR01"),//ADRESSE : CODE ADRESSE IMMEUBLE INEXISTANT DANS LE REFERENTIEL OI
FADR02("FADR02"),//ADRESSE : BATIMENT MANQUANT OU INEXISTANT DANS LE REFERENTIEL OI
FADR03("FADR03"),//ADRESSE : ESCALIER MANQUANT OU INEXISTANT DANS LE REFERENTIEL OI
FADR04("FADR04"),//ADRESSE : ETAGE MANQUANT OU INEXISTANT DANS LE REFERENTIEL OI
FIMP01("FIMP01"),//TRAITEMENT IMPOSSIBLE : PTO REQUISE
FIMP02("FIMP02"),//TRAITEMENT IMPOSSIBLE : PTO INEXISTANTE DANS LE REFERENTIEL OI
FIMP03("FIMP03"),//TRAITEMENT IMPOSSIBLE : PTO INCONNUE A L ADRESSE
FIMP04("FIMP04"),//TRAITEMENT IMPOSSIBLE : REF PRESTATION PM INEXISTANTE DANS LE REFERENTIEL OI
FIMP05("FIMP05"),//TRAITEMENT IMPOSSIBLE : REF PRESTATION PM ET ADRESSE INCOHERENTES
FIMP06("FIMP06"),//TRAITEMENT IMPOSSIBLE : TYPE DE COMMANDE IRRECEVABLE SUR CETTE REF PRESTATION PM
FIMP07("FIMP07"),//TRAITEMENT IMPOSSIBLE : PM INEXISTANT DANS LE REFERENTIEL OI
FIMP08("FIMP08"),//TRAITEMENT IMPOSSIBLE : PM ET ADRESSE INCOHERENTS
FIMP09("FIMP09"),//TRAITEMENT IMPOSSIBLE : COMMANDE IRRECEVABLE SUR CE PM
FIMP10("FIMP10"),//TRAITEMENT IMPOSSIBLE : COMMANDE IRRECEVABLE SUR CETTE ADRESSE
FIMP11("FIMP11"),//TRAITEMENT IMPOSSIBLE : ADRESSE INELIGIBLE TEMPORAIREMENT
FIMP12("FIMP12"),//TRAITEMENT IMPOSSIBLE : TYPE COMMANDE ERRONNE
FIMP13("FIMP13"),//TRAITEMENT IMPOSSIBLE : IDENTIFIANT COMMANDE INTERNE OC DEJA UTILISE
FIMP14("FIMP14"),//TRAITEMENT IMPOSSIBLE : IDENTIFIANT COMMANDE INTERNE OC INCONNUE
FIMP15("FIMP15"),//TRAITEMENT IMPOSSIBLE : CHAMPS OBLIGATOIRES MANQUANTS
FIMP16("FIMP16"),//TRAITEMENT IMPOSSIBLE : CHAMPS INCOHERENTS
FIMP17("FIMP17"),//TRAITEMENT IMPOSSIBLE : PTO INEXISTANTE
FIMP18("FIMP18"),//TRAITEMENT IMPOSSIBLE : PTO EXISTANTE
FIMP19("FIMP19"),//TRAITEMENT IMPOSSIBLE : PTO DEJA AFFECTEE A L'OC
FINT01("FINT01"),//ECHEC PRODUCTION : PB OU PM SATURE
FINT02("FINT02"),//ECHEC PRODUCTION : SATURATION VIRTUELLE PB OU PM
FINT03("FINT03"),//ECHEC PRODUCTION : HOTLINE OI INJOIGNABLE
FINT04("FINT04"),//ECHEC PRODUCTION : ABSENCE DE CONTINUITE OPTIQUE
FINT05("FINT05"),//ECHEC PRODUCTION : AFFAIBLISSEMENT TROP IMPORTANT
FINT06("FINT06"),//ECHEC PRODUCTION : ROUTE OPTIQUE DEJA UTILISEE
FINT07("FINT07"),//ECHEC PRODUCTION : INFORMATIONS ROUTE OPTIQUE ERRONEES
FINT08("FINT08"),//ECHEC PRODUCTION : POSITION BRASSAGE BAIE OPERATEUR INTROUVABLE
FINT09("FINT09"),//ECHEC PRODUCTION : POSITION BRASSAGE BAIE OPERATEUR DÉJÀ UTILISEE
FINT10("FINT10"),//ECHEC PRODUCTION : AUTRE PROBLEME TECHNIQUE
FINT11("FINT11"),//ECHEC PRODUCTION : INFRA TIERS INDISPONIBLE OU DELAI
FINT12("FINT12"),//ECHEC PRODUCTION : PBO NON CONFORME
FINT13("FINT13"),//ECHEC PRODUCTION : DEFAUT DE VERTICALITE
FAUT01("FAUT01"),//AUTRE MOTIF : COMMENTAIRES LIBRES
FRDV01("FRDV01"),//RDV : NOMBRE MAX DE MODIFICATIONS DE RDV DEPASSE
FRDV02("FRDV02"),//RDV : PAS DE PLAGES DE RDV DISPONIBLES SUR CES CRENEAUX
FRDV03("FRDV03"),//RDV : PLAGE DE RDV NON RESERVEE
FRDV04("FRDV04"),//RDV : ETAT RDV NON VALIDE 
FRDV05("FRDV05"),//RDV : RDV SUR PRODUIT NON FTTH 
FRDV06("FRDV06"),;//RDV : RDV SUR ADRESSE DIFFERENTE

private final String rejet;

    public String getRejet() {
        return rejet;
    }

    private Rejet(final String rejet) {
        this.rejet = rejet;
    }


}
